import countriesJson from "../../data/countries.json";
import { isZone } from "../../shared/utils/zones";
import type { CountryEntry } from "../../shared/utils/countries";

/**
 * The complete country list generated by `pnpm countries:generate`. It is the
 * source of truth for zones and the fallback when the live provider is down.
 */
export const bundledCountries: CountryEntry[] = countriesJson.flatMap((entry) =>
  /^[a-z]{2}$/.test(entry.code) && isZone(entry.zone)
    ? [{ code: entry.code, label: entry.label, zone: entry.zone }]
    : [],
);

